config/routes.rb
Rails.application.routes.draw do

  devise_for :users
    root  'projects#index'
    
    get 'projects' => 'projects#index'
    
    resources :newinfos do
      resources :comments, only: [:create, :destroy]
    end
    
    resources :users, only: [:index, :show]
    
    resources :papers do
    collection do
      get 'search'
      end
    end
  
    resources :members
    
    resources :sitemaps, only: [:index]
  
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
    belongs_to :newinfo
    belongs_to :user
end

app/models/member.rb
class Member < ApplicationRecord
    belongs_to :user
end

app/models/newinfo.rb
class Newinfo < ApplicationRecord
    belongs_to :user
    has_many :comments, dependent: :destroy
    
    validates :updated_at, presence: true
end

app/models/paper.rb
class Paper < ApplicationRecord
    belongs_to :user
    
    
 
    
    
end

app/models/project.rb
class Project < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :newinfos
  has_many :papers
  has_many :members
  
  has_many :comments, dependent: :destroy
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:nickname])
  end
  
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    
def create
comment = Comment.create(text: comment_params[:text], newinfo_id: comment_params[:newinfo_id], user_id: current_user.id)
redirect_to "/newinfos/#{comment.newinfo.id}"
end

def destroy
        
@newinfo = Newinfo.find(params[:newinfo_id])
        comment = @newinfo.comments.find(params[:id])
        if comment.user != current_user
            redirect_to request.referer
        end
        comment.destroy
        redirect_to request.referer
        
end


private
def comment_params
params.require(:comment).permit(:text).merge(user_id: current_user.id, newinfo_id: params[:newinfo_id])
end
  
end

app/controllers/members_controller.rb
class MembersController < ApplicationController
    before_action :move_to_index, except: [:index, :show]

  def index
      @members = Member.includes(:user).order(order: "ASC")
  end
  
def new 
end


def create 
  Member.create(name: member_params[:name],
  surname: member_params[:surname],
  name_in_alphabet: member_params[:name_in_alphabet],
  surname_in_alphabet: member_params[:surname_in_alphabet],
  e_mail: member_params[:e_mail],
  role: member_params[:role],
  affiliation: member_params[:affiliation],
  position: member_params[:position],
  left_on: member_params[:left_on],
  specialty: member_params[:specialty],
  image: member_params[:image],
  order: member_params[:order],
  user_id: current_user.id  
  )

end

def destroy
member = Member.find(params[:id])
member.destroy if member.user_id == current_user.id
end

def edit
@member = Member.find(params[:id])
end

def update
    member = Member.find(params[:id])
     if member.user_id == current_user.id
        member.update(member_params) 
     end
end


def show
@member = Member.find(params[:id])
end

private
def member_params
  params.permit(:name, :surname, :name_in_alphabet, :surname_in_alphabet, :e_mail, :role, :affiliation, :position, :entered_on, :left_on, :specialty, :image, :order )
end

def move_to_index
  redirect_to action: :index unless user_signed_in?
end

end

app/controllers/newinfos_controller.rb
class NewinfosController < ApplicationController
   before_action :move_to_index, except: [:index, :show]
  
  def index
    # productsテーブルから最新順に作品を２０件取得する
    @newinfos = Newinfo.includes(:user).order('updated_at DESC').page(params[:page]).per(10)
  end
  
  def new 
  end
  
  def create
     Newinfo.create(title: newinfo_params[:title],
     url: newinfo_params[:url],
     img: newinfo_params[:img],
     updated_at: newinfo_params[:updated_at], 
     user_id: current_user.id)
     Comment.create
  end
   
    def destroy
    newinfo = Newinfo.find(params[:id])
    newinfo.destroy if newinfo.user_id == current_user.id
    end
    
    def edit
    @newinfo = Newinfo.find(params[:id])
    end
    
    def update
    newinfo = Newinfo.find(params[:id])
     if newinfo.user_id == current_user.id
        newinfo.update(newinfo_params) 
     end
    end

  def show
    # productsテーブルから該当するidの作品情報を取得し@productの変数へ代入する処理を書いて下さい
    @newinfo = Newinfo.find(params[:id])
    @comments = @newinfo.comments.includes(:user)
    @comment =Comment.new
  end

  def search
    # 検索フォームのキーワードをあいまい検索して、productsテーブルから20件の作品情報を取得する
    @newinfos = []
  end
  
  
   
   private
   def newinfo_params
   params.permit(:title, :url, :img, :updated_at )
   end
   
  def move_to_index
  redirect_to action: :index unless user_signed_in?
  end

end

app/controllers/papers_controller.rb
class PapersController < ApplicationController
    before_action :move_to_index, except: [:index, :show, :search]
  
    def index
    @papers = Paper.includes(:user).order('firstappeared DESC').page(params[:page]).per(5)

    end

    def new
    end
    
    def create
    Paper.create(author: paper_params[:author], title: paper_params[:title], 
    journal: paper_params[:journal], number: paper_params[:number], 
    published: paper_params[:published], published_url: paper_params[:published_url],
    firstappeared: paper_params[:firstappeared], firstappeared_url: paper_params[:firstappeared_url],
    category: paper_params[:category],
    fiscalyear: paper_params[:fiscalyear],
    user_id: current_user.id )
    end
    
    def destroy
    paper = Paper.find(params[:id])
    paper.destroy if paper.user_id == current_user.id
    end
    
    def edit
    @paper = Paper.find(params[:id])
    end
    
    def update
    paper = Paper.find(params[:id])
     if paper.user_id == current_user.id
        paper.update(paper_params) 
     end
    end
    
  def show
    # productsテーブルから該当するidの作品情報を取得し@productの変数へ代入する処理を書いて下さい
    @paper = Paper.find(params[:id]) # 問題3ではこのコードは消して新しくコードを書いてください
  end

  def search
    # 検索フォームのキーワードをあいまい検索して、productsテーブルから20件の作品情報を取得する
    @papers = Paper.where('title Like(?) OR author Like(?)', "%#{params[:keyword]}%", "%#{params[:keyword]}%")
  end
  
  
    private
    def paper_params
    params.permit(:author, :title, :journal, :number, :published, :published_url, :firstappeared, :firstappeared_url, :category, :fiscalyear)
    end

    def move_to_index
    redirect_to action: :index unless user_signed_in?
    end

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
     def index
        @projects = Project.all
     end
end

app/controllers/sitemaps_controller.rb
class SitemapsController < ApplicationController
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    
    def show
    user = User.find(params[:id])
    @nickname = user.nickname
    @newinfos = user.newinfos.order("updated_at DESC")
    
    @papers = current_user.papers.order("updated_at DESC").page(params[:page])

    end
    
    

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/members_helper.rb
module MembersHelper
end

app/helpers/newinfos_helper.rb
module NewinfosHelper
end

app/helpers/papers_helper.rb
module PapersHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/sitemaps_helper.rb
module SitemapsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/members/create.html.erb
<div class="frame2" style="background-color: transparent;">  

<div class="show">
<h3> Submission completed.</h3>
    
        <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/members" >
          Members
          </a>
        </div>
</div>        
</div>

app/views/members/destroy.html.erb
<div class="frame2" style="background-color: transparent;">  

<div class="contents row"> <div class="success">
<h3> Deleted
</h3>

    <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/members" >
          Members
          </a>
    </div>


</div>

</div>

app/views/members/edit.html.erb
<div class="frame2" style="background-color: transparent;">  


<div class="show">
    
<%= form_tag("/members/#{@member.id}", method: :patch ) do %>
<h2> Edit member info
</h2>
    <p>Name jp: <input type="text" name="name" value="<%= @member.name %>" placeholder="Name jp"></p>
    <p>Surname jp: <input type="text" name="submit" value="<%= @member.surname %>" placeholder="Surname jp"></p>
    <p>Name en: <input type="text" name="name_in_alphabet" value="<%= @member.name_in_alphabet %>" placeholder="Name en"></p>
    <p>Surname en: <input type="text" name="surname_in_alphabet" value="<%= @member.surname_in_alphabet %>" placeholder="Surname en"></p>
    <p>E-mail: <input type="text" name="e_mail" value="<%= @member.e_mail %>" placeholder="[at]">
    </p><p font-size="2px">** Please use [at] for @.</p>
    </p>
 
    <p>Photo image: <input type="text" name="image" value="<%= @member.image %>" placeholder="Image URL"></p>
    
    
    <p>Role in the Lab: <input type="text" name="role" value="<%= @member.role %>" placeholder="Role in the lab"></p>
    <p>Specialty: <input type="text" name="specialty" value="<%= @member.specialty %>" placeholder="Specialty"></p>
    <p>Graduated form the Lab: <input type="date" name="left_on" value="<%= @member.left_on %>" placeholder="Graduated form the Lab">
    </p><p size="2px">* When the date of graduate is input, you will be listed in "Senior" members table. </p>

    <p>Current affiliation: <input type="text" name="affiliation" value="<%= @member.affiliation %>" placeholder="Affiliation"></p>
    <p>Current position: <input type="text" name="position" value="<%= @member.position %>" placeholder="Position"></p>
    
    
    

<input type="submit" value="SEND">
<% end %>
</div>

</div>

app/views/members/index.html.erb
<div class="frame2" style="background-color: transparent;">  

    
    
        <div class="user">
        <% if user_signed_in? %>  
          <div class="">
              <span class="user_nav">
                <%= link_to( "/members/new") do %>
                <font style="padding:4px;font-family:sans-serif;color:#fff; background:#86B0D2; border-radius:3px;">
                    submit members</font>
                <% end %>
                
              </span>
          </div>
        <% else %>
          <div class="">
              <span class="user_nav">
                  <p style="font-size:14px; font-family:sans-serif; color:#535353;">Submit members? please log in.</p> 
              </span>
          </div>
        <% end %>
        </div><!---user--->

<h2>Members</h2>
    <div class="members clearfix">
  
        
    <% @members.each do |member| %>  
      <% unless member.left_on.present? then %>
      
        <div class="child b1"> 
            
            <p class="circle1" style="background-image: url('<%= member.image %>')"; >
            </p>
            
            <div class="mem">
              <p><%= member.surname %> <%= member.name %>  
              <%= link_to "▶︎", "/members/#{member.id}", method: :get, class: "my-nav" %>
              </p
              > 
              <p><%= member.surname_in_alphabet.upcase %> <%= member.name_in_alphabet %></p>
              <p style="font-size:smaller"><%= member.role %></p>
            </div><!---mem--->
        </div><!---child b1--->
        
       <% end %>
    <% end %>
    
    </div>
    
    <h2>Seniors</h2>
    <div class="show">
    <% @members.each do |member| %>  
       <% if member.left_on.present? then %>
    
       <div >
       <p><%= member.surname %> <%= member.name %> / <%= member.surname_in_alphabet.upcase %> <%= member.name_in_alphabet %> 
       <%= link_to "▶︎", "/members/#{member.id}", method: :get, class: "my-nav"%></p>
       </div>
       <% end %>
    <% end %>
    </div> 
        
    
        
         
        <div class="pagenate">
        </div>
        
</div><!---frame--->          

app/views/members/new.html.erb
<div class="frame2" style="background-color: transparent;">  

<div class="show">

  <%= form_tag('/members', method: :post) do %>
  
    <h2>Submit members</h2>
    
    <p><input type="text" name="name" placeholder="name in Japanese"></p>
    <p><input type="text" name="surname" placeholder="surame in Japanese"></p>
    <p><input type="text" name="name_in_alphabet" placeholder="Name in alphabet"></p>
    <p><input type="text" name="surname_in_alphabet" placeholder="SURNAME in alphabet"></p>
    <p><input type="text" name="e_mail" placeholder="e-mail"></p>
    <p font-size="2px">** Please use [at] for @.</p>
    <p><input type="text" name="image" placeholder="face photo url"></p>
    <p><input type="text" name="role" placeholder="role in the lab"></p>
    <p><input type="text" name="affiliation" placeholder="current affiliation"></p>
    <p><input type="text" name="position" placeholder="current position"></p>
    <p>Entered in the lab <input type="date" name="entered_on" placeholder="entered_on"></p>
    <p>Graduated from the lab <input type="date" name="left_on" placeholder="graduated_on"></p>
    <p size="2px">* When the date of graduate is input, you will be listed in "Senior" members table. </p>

    <p><input type="submit" value="SEND"></p>

  <% end %>
  
</div>
</div>

app/views/members/show.html.erb
<div class="frame2" style="background-color: transparent;">  
<div class="members" style="margin-top: 20px;">
    
<%= form_for(@member) do |f| %>

        <p>[ News ID: <%= @member.id %> ]</p>
        
        <div class="photo"> 
            <p class="circle1" style="background-image: url('<%= @member.image %>')"; >
            </p>
        </div>
            
            <div class="smaller">
              <p><strong>Name jp/ en :　</strong><%= @member.surname %> <%= @member.name %> / 
              <%= @member.surname_in_alphabet.upcase %> <%= @member.name_in_alphabet %>,</p>
              <p><strong>Role in the Lab :　</strong><%= @member.role %></p>
              
              <p><strong>Specialty :　</strong><%= @member.specialty %></p>
              
              <p><strong>Graduated form the Lab :　</strong><%= @member.left_on %></p>
              <p><strong>Current affiliation :　</strong><%= @member.affiliation %></p>
              <p><strong>Current position :　</strong><%= @member.position %></p>
            
            <p><strong>E-mail :　</strong><%= @member.e_mail %> <font style="font-size:smaller">　　 *Please change [at] to @ </font></p>
            
  
<% end %>
</div>

   <div>    
    <% if user_signed_in? && current_user.id == @member.user_id %>
        <span class="my_button_show" >
        <ul>
          <li>
            <%= link_to 'Edit', "/members/#{@member.id}/edit", method: :get, class:"my_nav" %>
          </li>
          <li>
            <%= link_to 'Delete', "/members/#{@member.id}", method: :delete, class:"my_nav" %>
          </li>
        </ul>
        </span>
    <% end %>
    </div>
    
        <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/members" >
          Members
          </a>
        </div>
        
</div>

app/views/members/update.html.erb
<div class="frame2" style="background-color: transparent;">  


<div class="show">
<h3> Updated
</h3>
        <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/members" >
          Members
          </a>
        </div>


</div></div>

app/views/newinfos/create.html.erb
<div class="frame2" style="background-color: transparent;">  

<div class="show">
    <h3> Submission completed.</h3>
    
        <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/newinfos" >
          News
          </a>
        </div>

</div></div>

app/views/newinfos/index.html.erb
<div class="frame2" style="background-color: transparent;">  
    
        <div class="user">
        <% if user_signed_in? %>  
          <div class="">
              <span class="user_nav">
                <%= link_to( "/newinfos/new") do %>
                <font style="padding:4px;font-family:sans-serif;color:#fff; background:#86B0D2; border-radius:3px;">
                    submit news</font>
                <% end %>
                
              </span>
          </div>
        <% else %>
          <div class="">
              <span class="user_nav">
                  <p style="font-size:14px; font-family:sans-serif; color:#535353;">Submit news? please log in.</p> 
              </span>
          </div>
        <% end %>
        </div><!---user--->

    <h2>News</h2>

        <div class="parent">
          <% @newinfos.each do |newinfo| %>
          <div class="Leaderboard">
            <table>
            <tr>
            <th class="td1"><p><%= newinfo.updated_at&.strftime('%b %d, %Y') %></p></th>
            
            <th class="td2"><p><%= link_to "#{newinfo.title}", "/newinfos/#{newinfo.id}", method: :get %></p></th>

            </tr>
            </table>
          </div>
          <% end %>  
        </div><!---parent--->
          
        <div class="pagenate">
          <%= paginate(@newinfos) %>
        </div>     
</div><!---frame--->          

app/views/newinfos/new.html.erb
<div class="frame2" style="background-color: transparent;">
  
<div class="show">
  
  <%= form_tag('/newinfos', method: :post) do %>
    <h2>
      Submit news
    </h2>
    <p>Update on <input type="date" name="updated_at" placeholder="updated on"></p>
    
    <p><input type="text" name="title" placeholder="headline"></p>
    <p><input type="text" name="url" placeholder="link site url"></p>
    <p><input type="text" name="img" placeholder="image url"></p>

    <p><input type="submit" value="SEND"></p>
  <% end %>

</div></div>  

app/views/newinfos/show.html.erb
<div class="frame2" style="background-color: transparent;">  
<div class="newinfos" style="margin-top: 20px;">

<%= form_for(@newinfo) do |f| %>

        
        <p>[ News ID: <%= @newinfo.id %> ]</p>
        
        <div class="smaller">
        <p><strong>Updated: </strong><%= @newinfo.updated_at.strftime('%b %d, %Y') %></p>
        <p><strong>Sender: </strong> <%= @newinfo.user.nickname %></p>
        <p><strong>Headline:  </strong><font size="3px"><%= @newinfo.title %></font></p> 
   
   
        <div class="newinfo_img" >    
        <img src="<%= @newinfo.img %>" width="340" height="200">
        </div>
    
    <p><strong>Link: </strong>
        <a href="<%= @newinfo.url %>"><font style="color:#333;"><%= @newinfo.url %></font></a>
    </p>    
   
       </div>
<% end %>         
       
        
        <div class="comments_container"><div class="smaller"><strong>Comments: </strong></div>
            <% if current_user %>
              <% form_tag("/newinfos/#{@newinfo.id}/comments", method: :post) do %>
              <textarea name="text" placeholder="Enter your comment." rows="2" cols="30"></textarea>
              <input type="submit" value="SEND">
              <% end %>
            <% end %>
        </div>



<div class="smaller"> 
<div class="comments">
    <div>           
    <% if user_signed_in? %>
        <%= form_with(model: [@newinfo, @comment], local: true) do |form| %>
        <%= form.text_area :text, placeholder: "Enter your comments.", rows: "2" %>
        <%= form.submit "SEND" %>
        <% end %>
    <% else %>
        <font style="color:#4682b4">__Please log in and give us your comments.__</font>
    <% end %>
    </div>
          
            
<% if @comments %>
        <% @comments.each do |comment| %>
         <p>
         <strong><% link_to comment.user.nickname, "/users/#{comment.user_id}" %></strong>
         <font style="color: #ed6d3d; font-size:small;"><%= comment.user.nickname %> </font>
         <%= comment.text %>
         
         <% if user_signed_in? && current_user.id == comment.user_id %> 
          <span>
          <%= link_to 'Delete', newinfo_comment_path(@newinfo, comment), method: :delete, class: "my-nav2" %>
          </span>
         <% end %>
         
         </p>
        <% end %>
<% end %>

</div>
</div> 
  
            
            
            
         
</div> 


<div>    
  <% if user_signed_in? && current_user.id == @newinfo.user_id %>
      
        
        <span class="my_button_show" >
        <ul>
          <li>
            <%= link_to 'Edit', "/newinfos/#{@newinfo.id}/edit", method: :get, class:"my_nav" %>
          </li>
          <li>
            <%= link_to 'Delete', "/newinfos/#{@newinfo.id}", method: :delete, class:"my_nav" %>
          </li>
        </ul>
        </span>
      
    <% end %>
</div> 
    
        <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/newinfos" >
          News
          </a>
        </div>

  
</div>

app/views/papers/create.html.erb
<div class="frame3" style="background-color: transparent;">  

<div class="show">
    <h3> Submission completed.</h3>
    
        <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/papers" >
          Papers
          </a>
        </div>
</div>
</div>

app/views/papers/destroy.html.erb
<div class="frame2" style="background-color: transparent;">  

<div class="contents row"> <div class="success">
<h3> Deleted
</h3>

    <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/papers" >
          Papers
          </a>
    </div>


</div>

</div>

app/views/papers/edit.html.erb
<div class="frame2" style="background-color: transparent;">  


<div class="show">

<%= form_tag("/papers/#{@paper.id}", method: :patch ) do %>
<h2> Edit paper info
</h2>
    <p>Authors: <input type="text" name="author" value="<%= @paper.author %>" placeholder="Author"></p>
    <p>Subtitle: <textarea name="title" placeholder="string" rows="10" cols="30"><%= @paper.title %></textarea></p>
    <p>Journal name: <input type="text" name="journal" value="<%= @paper.journal %>" placeholder="Journal name"></p>
    <p>Journal info: <input type="text" name="number" value="<%= @paper.number %>" placeholder="Journal info"></p>
    <p>Published date: <input type="date" name="published" value="<%= @paper.published %>" placeholder="Published date"></p>
    <p>Published URL: <input type="text" name="published_url" value="<%= @paper.published_url %>" placeholder="URL of Published"></p>
    <p>First appearanced date: <input type="date" name="firstappeared" value="<%= @paper.firstappeared %>" placeholder="Firstappeared date"></p>
    <p>First appearanced URL: <input type="text" name="firstappeared_url" value="<%= @paper.firstappeared_url %>" placeholder="URL of Firstappeared"></p>
    
    
    

<input type="submit" value="SENT">
<% end %>

</div>
</div>

app/views/papers/index.html.erb
<div class="frame2" style="background-color: transparent;">  

        <div class="user">
        <% if user_signed_in? %>  
          <div class="">
              <span class="user_nav">
                <%= link_to( "/papers/new") do %>
                <font style="padding:4px;font-family:sans-serif;color:#fff; background:#86B0D2; border-radius:3px;">
                    submit papers</font>
                <% end %>
                
              </span>
          </div>
        <% else %>
          <div class="">
              <span class="user_nav">
                  <p style="font-size:14px; font-family:sans-serif; color:#535353;">Submit papers? please log in.</p> 
              </span>
          </div>
        <% end %>
        </div><!---user--->

    <h2>Papers</h2>
        
        <div class="search_area">
            <div class="search">
            <%= form_tag('/papers/search', method: :get) do %>
                <input class="search__query" name="keyword" placeholder="by author or subject" type="text" value="">
                <button class="btn-search" title="検索" type="submit">
                <i class="icon-search">Search</i>
                </button>
                </input>
            <% end %>
            </div>
        </div><!---class search area--->


    <% @papers.each do |paper| %>
    <div class="papers">
            
         <p><%= paper.author %></p> 
         <p class="paper_title">"<%= paper.title %>"</p> 
         <p><%= paper.journal %>, <%= paper.number %></p>
         <p><a href="<%= paper.published_url %>"><%= paper.published_url %></a> , published on <%= paper.published %></p>
         <p><a href="<%= paper.firstappeared_url %>"><%= paper.firstappeared_url %></a>, first appeared on <%= paper.firstappeared %></p> 
         <p><%= paper.category %></p>

        
        <div class="my_area">     
        <% if user_signed_in? && current_user.id == paper.user_id %> 
            <span class="my_name"> 
            　<a href="/users/<%= paper.user_id %>">
                <font style="color:#ff8c00; font-family:sans-serif;"> <%= paper.user.nickname %></font>
          　   </a>
            </span>
            
            <span class="my_button">
                <ul><li>
                <a><%= image_tag 'arrow072_09.png' %></a> 
                <ul>
                    <li>
                    <%= link_to 'Details', "/papers/#{paper.id}", method: :get, class: "my-nav" %>
                    </li>
                    <li>
                    <%= link_to 'Edit', "/papers/#{paper.id}/edit", method: :get, class: "my-nav" %>
                    </li>
                    <li>
                    <%= link_to 'Delete', "/papers/#{paper.id}", method: :delete, class: "my-nav" %>
                    </li>
                </ul>
                </li></ul>
            </span>
            
        <% end %>
        </div>

    </div><!---class papers--->  
    <% end %>

        
<div class="pagenate">
<%= paginate(@papers) %>
</div>  

        
</div>

app/views/papers/search.html.erb
  <div class="frame3">
              
              <h3>Search</h3>
                
  <div class="search_area">
                
              <div class="search">
              <%= form_tag('/papers/search', method: :get) do %>
                <input class="search__query" name="keyword" placeholder="by author or subject" type="text" value=""><button class="btn-search" title="検索" type="submit">
                  <i class="icon-search">Search</i></button>
              </input>
              <% end %>
              </div>
              
          <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/papers" >
          Papers
          </a>
          </div>
      
  </div>
          
                <h3>
                  Result
                </h3>
              
              
                  <% @papers.each do |paper| %>
    <div class="papers">
            
           <p><%= paper.author %></p> 
         <p class="paper_title">"<%= paper.title %>"</p> 
         <p><%= paper.journal %>, <%= paper.number %></p>
         <p><a href="<%= paper.published_url %>"><%= paper.published_url %></a> , published on <%= paper.published %></p>
         <p><a href="<%= paper.firstappeared_url %>"><%= paper.firstappeared_url %></a>, first appeared on <%= paper.firstappeared %></p> 
         <p><%= paper.category %></p>
         <p><%= paper.fiscalyear %></p>
        
        
        <div class="my_area">     
        <% if user_signed_in? && current_user.id == paper.user_id %> 
        
            <span class="my_name"> 
            　<a href="/users/<%= paper.user_id %>">
                <font style="color:#ff8c00; font-family:sans-serif;"> <%= paper.user.nickname %></font>
          　   </a>
            </span>
            
            
            <span class="my_button">
                <ul><li>
                <a><%= image_tag 'arrow072_09.png' %></a> 
                <ul class="">
                    
                    <li>
                    <%= link_to "Details", paper_path(paper.id), method: :get %>
                    </li>
                    
                    <li>
                    <font><%= link_to 'Edit', "/papers/#{paper.id}/edit", method: :get %></font>
                    </li>
                    <li>
                    <%= link_to 'Delete', "/papers/#{paper.id}", method: :delete %>
                    </li>
                </ul>
                </li></ul>
            </span>
            
        <% end %>
        </div>

         
    
        
    </div><!---class papers--->  
    <% end %>
            
            
        
          
  </div>

app/views/papers/update.html.erb
<div class="frame2" style="background-color: transparent;">
<div class="show">  

<h3> Updated
</h3>
        <div class="gnav_menu_backbutton">
          <font style="font-size:smaller; font-weight:noemal;">Return to</font> 
          <a href="/papers" >
          Papers
          </a>
        </div>


</div></div>